<?php
$currentTopic = $this->getCurrentTopic();
echo '<h1>'.$currentTopic["title"].'</h1>';
?>
<ul>
	<?php 
		foreach($this->getQasById() as $qa){
			echo '<li>';
				echo '<h4><a href="/support/'.$qa["url"].'">'.$qa["question"].'</a></h4>';
				echo '<p>'.((strlen($qa['answer_summary']) > 200) ? substr($qa['answer_summary'],0,200).'...' : $qa['answer_summary']).'</p>';
			echo '</li>';
		}
	?>
</ul>